### ISSUE TITLE
Failling test for test_word_counter.py (macOS)

### ISSUE THREAD

**Issue by victordomingos** [victordomingos/Count-files#54]
```
$ python3.7 tests/test_word_counter.py
LOCATION:  tests/compare_tables/test_2columns_sorted.txt
LOCATION:  tests/compare_tables/test_2columns_most_common.txt
LOCATION:  tests/data_for_tests

LOCATION:  tests/compare_tables/2columns_sorted.txt
LOCATION:  tests/compare_tables/2columns_most_common.txt
.LOCATION:  tests/data_for_tests
LOCATION:  tests/compare_tables/test_show_result_no_list.txt
LOCATION:  tests/compare_tables/show_result_no_list.txt
F
======================================================================
FAIL: test_show_result_for_search_files (__main__.TestWordCounter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_word_counter.py", line 57, in test_show_result_for_search_files
    shallow=False), True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 2 tests in 0.012s

FAILED (failures=1)
```

**Comment by NataliaBondarenko** [comment]
Hello!
files must be the same(characters, spaces, line breaks)
show_result_no_list.txt and test_show_result_no_list.txt

**Comment by victordomingos** [comment]
Doing a fresh install of this package:
```
$ git clone https://github.com/victordomingos/Count-files.git
Cloning into 'Count-files'...
remote: Counting objects: 1199, done.
remote: Compressing objects: 100% (111/111), done.
remote: Total 1199 (delta 90), reused 121 (delta 48), pack-reused 1031
Receiving objects: 100% (1199/1199), 2.12 MiB | 1.97 MiB/s, done.
Resolving deltas: 100% (556/556), done.
$ cd Count-files/
$ pip3 install -e .
Obtaining file:///Users/retina13/Dropbox/Count-files
Requirement already satisfied: puremagic==1.4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from countfiles==1.4) (1.4)
Requirement already satisfied: argparse in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from puremagic==1.4->countfiles==1.4) (1.4.0)
Installing collected packages: countfiles
  Running setup.py develop for countfiles
Successfully installed countfiles
```

Checking git status before running the test:
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
```

Then running the test:
```
$ python3 tests/test_word_counter.py 
LOCATION:  tests/compare_tables/test_2columns_sorted.txt
LOCATION:  tests/compare_tables/test_2columns_most_common.txt
LOCATION:  tests/data_for_tests
                                                                                                                                                                                   
LOCATION:  tests/compare_tables/2columns_sorted.txt
LOCATION:  tests/compare_tables/2columns_most_common.txt
.LOCATION:  tests/data_for_tests
LOCATION:  tests/compare_tables/test_show_result_no_list.txt
LOCATION:  tests/compare_tables/show_result_no_list.txt
F
======================================================================
FAIL: test_show_result_for_search_files (__main__.TestWordCounter)
Testing def show_result_for_search_files. Search by extension.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_word_counter.py", line 57, in test_show_result_for_search_files
    shallow=False), True)
AssertionError: False != True

----------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (failures=1)
```

In the end, git shows a changed file. Is this an expected behaviour or a bug?
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   tests/compare_tables/test_show_result_no_list.txt

no changes added to commit (use "git add" and/or "git commit -a")
```

Checking the difference (pasting a screenshot as the text copied does not show the whole picture in this case):
```
$ git diff tests/compare_tables/test_show_result_no_list.txt
```
<img width="891" alt="captura de ecra 2018-06-26 as 10 56 36" src="https://user-images.githubusercontent.com/18650184/41904175-a5062506-792f-11e8-88de-11a35bfb8b22.png">

**Comment by NataliaBondarenko** [comment]
it's carriage return. It is necessary to write different tests for the OS. Previously, this was not, it appeared after adding feedback.

**Comment by NataliaBondarenko** [comment]
create files on your computer with the same names, but the content will match the result of the CLI in the Mac OS.

**Comment by victordomingos** [comment]
So, I need to create a shell output file for that test, right? What is the exact procedure you have used to create the windows version of the test file?

**Comment by NataliaBondarenko** [comment]
There are no special procedures. Now it works as it should.
If something changes later, you will see the difference.
```
from contextlib import redirect_stdout
from countfiles.utils.word_counter import show_2columns, show_result_for_search_files
from countfiles.utils.file_handlers import count_files_by_extension, search_files


data = search_files('C:/Users/Net/Count-files/tests/data_for_tests', extension='.', include_hidden=False, recursive=True)
test1 = 'C:/Users/Net/Count-files/tests/compare_tables/win_show_result_no_list.txt'
with open(test1, 'w') as f:
    with redirect_stdout(f):
        show_result_for_search_files(files=data, no_list=True, no_feedback=True)
```

**Comment by victordomingos** [comment]
Well, since that darwin test file does not exist, I have a test failing on macOS.

```
$ python3 tests/test_word_counter.py 
LOCATION:  tests/compare_tables/test_2columns_sorted.txt
LOCATION:  tests/compare_tables/test_2columns_most_common.txt
LOCATION:  tests/data_for_tests
                                                                                                                                                                                                                                                                              
LOCATION:  tests/compare_tables/2columns_sorted.txt
LOCATION:  tests/compare_tables/2columns_most_common.txt
.LOCATION:  tests/data_for_tests
LOCATION:  tests/compare_tables/test_show_result_no_list.txt
LOCATION:  tests/compare_tables/darwin_show_result_no_list.txt
E
======================================================================
ERROR: test_show_result_for_search_files (__main__.TestWordCounter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_word_counter.py", line 64, in test_show_result_for_search_files
    shallow=False), True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/filecmp.py", line 52, in cmp
    s2 = _sig(os.stat(f2))
FileNotFoundError: [Errno 2] No such file or directory: 'tests/compare_tables/darwin_show_result_no_list.txt'

----------------------------------------------------------------------
Ran 2 tests in 0.014s

FAILED (errors=1)
```

**Comment by NataliaBondarenko** [comment]
Yes, edit and run. The file must be created in the Mac OS.
```
from contextlib import redirect_stdout
from countfiles.utils.word_counter import show_2columns, show_result_for_search_files
from countfiles.utils.file_handlers import count_files_by_extension, search_files


data = search_files('YOUR_PATH_TO_PROJECT/tests/data_for_tests', extension='.', include_hidden=False, recursive=True)
test1 = 'YOUR_PATH_TO_PROJECT/tests/compare_tables/darwin_show_result_no_list.txt'
with open(test1, 'w') as f:
    with redirect_stdout(f):
        show_result_for_search_files(files=data, no_list=True, no_feedback=True)
```

**Comment by victordomingos** [comment]
Done. I added the file and all tests pass now.

**Comment by victordomingos** [comment]
I am getting this error again:

```
$ python3.7
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
$ python3.7 tests/test_word_counter.py
.E
======================================================================
ERROR: test_show_result_for_search_files (__main__.TestWordCounter)
Testing def show_result_for_search_files. Search by extension.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_word_counter.py", line 72, in test_show_result_for_search_files
    shallow=False), True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/filecmp.py", line 52, in cmp
    s2 = _sig(os.stat(f2))
FileNotFoundError: [Errno 2] No such file or directory: 'tests/compare_tables/darwin_show_result_list.txt'

----------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (errors=1)
```

Not sure if something has changed in the expected output, or if there is some kind of difference between different macOS versions...  I confess I still have to learn pretty much everything about testing. However, I think that, if we need to rebuild the comparison file at each install, we should add it somewhere as automated action.

**Comment by NataliaBondarenko** [comment]
Hello! A standard file must be created for each computer separately. paths on different OS and on different PC may differ. The names of the files you created earlier do not match the ones specified in the def test_show_result_for_search_files. You can rename them. The name of the standard file and the name of the test file are in the gitignore. so I do not transfer files from Windows to the repository.

**Comment by victordomingos** [comment]
Can’t that process be automated?

**Comment by NataliaBondarenko** [comment]
almost done
